Develop wake steering lookup table toolset
NREL/wind-hybrid-open-controller pull request #43
Opened 2024-12-10 00:11 UTC by misi9170

Will add a detailed description in time. Combines utilities from lookup_table_tools and flasc related to the design of lookup table-based wake steering controllers.

2025-01-15 20:55 UTC, misi9170 commented
I've now extended the lookup-based_wake_steering_florisstandin example to include a hysteresis option, and updated the documentation accordingly.

2025-01-21 18:00 UTC, misi9170 commented
After discussions with @paulf81 and @ejsimley , I have decided to leave out the spline approximator. This tool would have allowed users to specify offset lookup tables with a reduced number of datapoints, which could be helpful in some circumstances, but is likely to be more nuanced than a general tool would afford. However, I'm making a note of it here in case there is future interest in such a tool (which we can then port over from another older repository).

2025-01-21 20:20 UTC, misi9170 commented
I've now added documentation, and this PR is ready for review. The documentation may finally be reorganized some (and API documentation added), but I decided to leave that for a separate pull request.

2025-02-07 23:14 UTC, ejsimley requested changes
Thanks for consolidating these lookup table functions here! This looks good overall. I left several comments where I thought we could make some functions more general and improve the interpolation. We can discuss those ideas more if you'd like before making any changes.

2025-02-10 16:56 UTC, misi9170 commented
Thanks for the review @ejsimley ! I'm going to start working through your comments now

2025-02-10 18:32 UTC, misi9170 commented on whoc/design_tools/wake_steering_design.py
> +    interpolant = LinearNDInterpolator(points=points, values=values, fill_value=np.nan)
Thanks for the suggestion @ejsimley---I've now made this change and added some extra tests for the interpolator.

2025-02-10 19:12 UTC, misi9170 commented on whoc/design_tools/wake_steering_design.py
> +        wd_std=wd_std,
Good suggestion---I've now done this. I considered allowing the user to pass an instantiated UncertainFlorisModel but decided against it, figuring that if users want full control over the design process, they should use the `YawOptimizerSerialRefine` directly and avoid these `build_xx_wake_steering_lookup_table()` functions. However, I need to document that better (that these are a starting point, but users who want more control should use FLORIS' methods directly)

2025-02-10 20:05 UTC, misi9170 commented on whoc/design_tools/wake_steering_design.py
> +    for j in range(1, len(ws_array)):
No good reason! I think I was feeling that wind speed and TI were more "linear", and wind direction more "circular", but that is not actually a good reason to only apply the rate limit one way---I've now changed that!

2025-02-11 18:40 UTC, paulf81 commented on examples/lookup-based_wake_steering_florisstandin/compare_yaw_offset_designs.py
> +    df_opt_rate_limited = wsd.apply_static_rate_limits(
I'm ok leaving this in, but I think in general we've found this generally not too preferable approach versus rate limiting/filtering in the time domain.  Maybe we just add some comments to the effect that this was an idea but no longer preferred

2025-02-11 18:42 UTC, paulf81 reviewed
I think we should add a README.md file to examples/lookup-based_wake_steering_florisstandin

2025-02-11 18:49 UTC, paulf81 commented on whoc/design_tools/wake_steering_design.py
> +    wd_max: float = 360,
Totally up to you, but I would do 360.0 to insist on it being a float.  But looking around I think either is fine

2025-02-11 18:52 UTC, paulf81 commented on whoc/design_tools/wake_steering_design.py
> +        ws_max (float, optional): The maximum wind speed in m/s. Defaults to 8.
I was looking into the code and note that use add .001 to ws_max, so it could be worth noting that the arrays will be defined with ws_max inclusive, just to make the behavior clear.  So in the default 
```
>>> np.arange(8,8.001,1)
array([8.])
```

2025-02-11 18:54 UTC, paulf81 commented on whoc/design_tools/wake_steering_design.py
> +def apply_static_rate_limits(
Made the comment elsewhere but wanted to find a way this method is probably not preferred to putting limits in the time domain.  This is forcing the controller to sub-optimal angles even if the wind direction changes slowly (freely admit this was I think my idea originally...)

2025-02-11 18:57 UTC, paulf81 commented on whoc/design_tools/wake_steering_design.py
> +    switching_idx = np.argwhere(np.diff(offsets, axis=0) >= yaw_rate_threshold*wd_step)
Makes sense to me

2025-02-11 19:01 UTC, paulf81 commented on whoc/design_tools/wake_steering_visualization.py
> +    # Construct array of offets
typo

2025-02-11 19:05 UTC, paulf81 approved these changes
Left only minor optional comments, looks really great, thanks for the thorough job, this is very useful to have all consolidated and cleaned up!!

2025-05-05 17:31 UTC, misi9170 commented on whoc/design_tools/wake_steering_design.py
> +    switching_idx = np.argwhere(np.diff(offsets, axis=0) >= yaw_rate_threshold*wd_step)
I've now update the methodology a bit for hysteresis, which addresses this comment. I'll write a more detailed explanation of the change as a stand-alone comment soon.

2025-05-05 19:03 UTC, misi9170 commented
> I think we should add a README.md file to examples/lookup-based_wake_steering_florisstandin

@paulf81 Thanks for the suggestion here. In WHOC, I've so far avoided putting readme's in each of the example folder and instead provided information about each example in docs/examples.md. Is that suitable?

2025-05-05 19:10 UTC, misi9170 commented
@ejsimley , I think I've now addressed your comments. In particular:
- The basic lookup table design tools `build_simple_wake_steering_lookup_table()` and `build_uncertain_wake_steering_lookup_table` now accept the possibility of optimizing over a range of TIs, specified by `ti_resolution`, `ti_min`, `ti_max`, consistent with how wind speeds and wind directions are handled
- Plotting tools are for a specific TI value: if `df_opt` contains only a single TI, `ti_plot` does not need to be specified, but if multiple TI values are present in `df_opt` then the user _must_ specify `ti_plot`.
- Handling the possibility of jumps between same-signed offsets for hysteresis was a bit more complicated. See paragraph below.

Hysteresis zones are now defined by the `yaw_rate_threshold`, which determines the change in yaw angle (as a function of wind direction) required to establish a hysteresis zone. The wind direction at which this threshold is exceeded is taken as the center location for a hysteresis zone, and the zone's width is now specified by the keyword argument `min_zone_width`. In prior implementations, the zone's width was found by determining when the offset returned to zero, using `min_zone_width` as a lower bound; now, the zone width is simply set as `min_zone_width` without checking that the offset returns to zero. However, if multiple zones overlap (because the yaw rate threshold is exceeded at nearby wind directions), those zones are combined into a single zone.

2025-05-05 19:21 UTC, misi9170 commented
Hi @paulf81, @ejsimley 

It took me a long time to come back to addressing your suggestions; sorry about that. If I could bother you for a rereview, I'd appreciate that. It's not particularly urgent. See the comments above for specifics about the changes I made to address your larger comments.

2025-05-12 19:36 UTC, ejsimley requested changes
@misi9170, thanks for making these changes to the wake steering tools! It will be helpful to be able to include TI in the optimizations now. I also appreciate being able to select a particular TI when plotting the yaw offsets.

I like the changes to the hysteresis zone definition, defining a minimum zone width and using the yaw rate threshold to identify hysteresis directions. I just had some comments about how overlapping hysteresis regions get combined. I think some edge cases where regions wrap around 0 degrees aren't getting handled correctly. I included a couple ideas, but there are still some cases that wouldn't get combined correctly. If you agree that the code should be changed, we can talk about these ideas more. 

Otherwise, I just had a couple optional comments in other places.

2025-05-12 19:36 UTC, ejsimley commented on whoc/design_tools/wake_steering_design.py
> +                if hysteresis_wds[-1][1] > hysteresis_wds[0][0]:
Is the objective here to consolidate the first and last regions if they overlap around 0 degrees? Trying some scenarios, here are some examples where the regions wouldn't get combined:
`hysteresis_wds = [(3, 7), (359, 3)]`
`hysteresis_wds = [(359, 1), (357, 359)]`

I think this could be changed to `hysteresis_wds[-1][1] >= hysteresis_wds[0][0]`

2025-05-12 19:36 UTC, ejsimley commented on whoc/controllers/lookup_based_wake_steering_controller.py
> +                    if zone[0] < wind_directions[t] < zone[1]:
Does this need to be changed to account for zones that include 0 degrees (e.g., zone[0] == 355, zone[1] == 3)

2025-05-12 21:32 UTC, misi9170 commented on whoc/design_tools/wake_steering_visualization.py
> +        ax.plot(wd_array, offsets, color=color, linestyle=linestyle, alpha=alpha, label=label)
My preference on this is to let the user call `ax.legend()` on the returned output `ax`. That allows the user to more easily specify other arguments to `legend()` so they control how it looks

2025-05-12 21:33 UTC, misi9170 commented on whoc/design_tools/wake_steering_design.py
> +    wind_rose = create_uniform_wind_rose(
Yeah, I'm not sure what the protocol is on this. I tend to define the "main" functionality near the top of the file, and helpers later on, but you're right that it means that the function appears "before" it is defined.

2025-05-12 21:34 UTC, misi9170 commented
Thanks @ejsimley ! I had thought I'd figured out combining the hysteresis zones around the 0/360 divide, but apparently not---I'll look into that and let you know when I think I've fixed it

2025-05-13 17:39 UTC, ejsimley commented on whoc/design_tools/wake_steering_design.py
> +    wind_rose = create_uniform_wind_rose(
That works too. No need to change anything.

2025-05-13 18:42 UTC, misi9170 commented on whoc/design_tools/wake_steering_design.py
> +                    and hysteresis_wds[i_h][0] <= hysteresis_wds[i_h+1][1]):
This last edge case you suggested is a tricky one! I've broken out the consolidation of the hysteresis zones into it's own function, partly just so that I can test it better. It's passing the "easier" tests, but it does indeed fail on this last one (two zones, both crossing the 360/0 divide). I'll see if I can figure that case out.

2025-06-09 23:59 UTC, misi9170 commented on whoc/design_tools/wake_steering_design.py
> +                    and hysteresis_wds[i_h][0] <= hysteresis_wds[i_h+1][1]):
Ok, finally I got this one! Had to reorganize the zone combining code some.

2025-06-10 00:03 UTC, misi9170 commented
Hi @ejsimley ,

After some swearing and soul-searching, I revamped the zone combination algorithm and I think it's now working as intended. I guess I can't be sure that there isn't some edge case that could slip by, I think this is working pretty well now. I've added various possible test scenarios to `test_consolidate_hysteresis_zones()` in tests/wake_steering_design_test.py.

If that all looks good to you, I think I can proceed to merging this in.

2025-06-18 23:10 UTC, merged